version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ '/usr/src/app/entrypoint.sh' ]
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=manage.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.Config
      - DATABASE_URL=postgresql://postgres:postgres@api-dev-db:5432/api_dev
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SHARED_SECRET_KEY=${SHARED_SECRET_KEY}

    depends_on:
      - api-dev-db
    
  api-dev-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
